FROM node:23-slim

WORKDIR /app

# Install the application dependencies
COPY . .
RUN npm install

EXPOSE 3000

# Setup an app user so the container doesn't run as the root user
RUN useradd app
USER app

# RUN APP
CMD ["node", "app.js"]