FROM python:3.11-slim

WORKDIR /app

# Install the application dependencies
COPY . .


RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

# Setup an app user so the container doesn't run as the root user
RUN useradd app
USER app

# RUN APP
CMD ["gunicorn", "app:app", "--bind", "0.0.0.0:5000"]